### ISSUE TITLE
Generate graph

### ISSUE THREAD

**Issue by chengzhangsuper** [TomStog/Infrared-BP#4]
I would like to ask what software is used to generate the regression curve graph of the dynamic interaction between frame standard deviation and systolic blood pressure/diastolic blood pressure in the paper, and how is it generated?

**Comment by chengzhangsuper** [comment]
Hello, what problem did the polynomial linear regression model solve in your paper? Can it be replaced with another model? Thank you. I feel like I am too stupid and cannot understand many places. Thank you very much for your answer.

**Comment by TomStog** [comment]
1) All the graphs were generated in Python. I found some similar code to do that online.

2) The problem that was tackled was the following. We wanted to have an algorithm that would take video as input and would print blood pressure levels as output. Pulse Transit Time is the in between step. Each pair of videos generates a pulse transit time and via a regression model (any regression model you want) we are able to map the pulse transit time with the blood pressure levels.
